# select adversarial features based on correlation on benign samples 
adversarial_features: [['src2dst_packets'],
                      ['src2dst_bytes'],
                      ['dst2src_packets'],
                      ['dst2src_bytes'],
                      #['src2dst_min_ps'],beacuse min would not fit in generation and hard to allign it with tcp/ip
                      ['src2dst_max_ps'],
                      #['dst2src_min_ps'], beacuse min would not fit in generation and hard to allign it with tcp/ip
                      ['dst2src_max_ps'],

                      ['src2dst_packets', 'src2dst_bytes'], # corr = 0.47
                      #['src2dst_packets', 'dst2src_packets'], corr = 0.91
                      #['src2dst_packets', 'dst2src_bytes'], corr = 0.87
                      #['src2dst_packets', 'src2dst_min_ps'],
                      ['src2dst_packets', 'src2dst_max_ps'], #corr = .17
                      #['src2dst_packets', 'dst2src_min_ps'],
                      ['src2dst_packets', 'dst2src_max_ps'], # corr = .39
                      
                      ['src2dst_bytes', 'dst2src_packets'], # corr = .36

                      ['src2dst_bytes', 'dst2src_bytes'],  #corr = 0.24
                      #['src2dst_bytes', 'src2dst_min_ps'],
                      ['src2dst_bytes', 'src2dst_max_ps'],  #corr = 0.32
                     # ['src2dst_bytes', 'dst2src_min_ps'],
                      ['src2dst_bytes', 'dst2src_max_ps'],  # corr = 0.05
                      #['dst2src_packets', 'dst2src_bytes'],
                      #['dst2src_packets', 'src2dst_min_ps'],
                      ['dst2src_packets', 'src2dst_max_ps'], #corr = 0.11
                     # ['dst2src_packets', 'dst2src_min_ps'],
                      ['dst2src_packets', 'dst2src_max_ps'], #corr = .2
                     # ['dst2src_bytes', 'src2dst_min_ps'],
                      ['dst2src_bytes', 'src2dst_max_ps'], #corr = 0.08
                      #['dst2src_bytes', 'dst2src_min_ps'],
                      #['dst2src__bytes', 'dst2src_min_ps'],
                      ['dst2src_bytes', 'dst2src_max_ps']] #corr = 0.49
                      #['src2dst_min_ps', 'src2dst_max_ps'], 
                      #['src2dst_min_ps', 'dst2src_min_ps'],
                      #['src2dst_min_ps', 'dst2src_max_ps']]

# the following should be repeated as the gan collapesed and generated output are not good
repeated_adversarial_features : [['dst2src_bytes', 'src2dst_max_ps'],
                                  ['dst2src_packets', 'dst2src_max_ps'],
                                  ['src2dst_bytes', 'dst2src_bytes'],
                                  ['src2dst_bytes', 'dst2src_max_ps'],
                                  ['src2dst_bytes', 'dst2src_packets'],
                                  ['src2dst_bytes', 'src2dst_max_ps'],
                                  ['src2dst_packets'],
                                  ['src2dst_packets', 'dst2src_max_ps'],
                                  ['src2dst_packets', 'src2dst_bytes'],
                                  ['src2dst_packets', 'src2dst_max_ps']
                                  ]

features: ['bidirectional_packets','bidirectional_bytes','bidirectional_min_ps',
                            'bidirectional_mean_ps','bidirectional_stddev_ps', 'bidirectional_max_ps' ,
                            'bidirectional_min_piat_ms','bidirectional_mean_piat_ms',
                            'bidirectional_stddev_piat_ms', 'bidirectional_max_piat_ms', 'bidirectional_syn_packets' ,
                            'bidirectional_cwr_packets', 'bidirectional_ece_packets','bidirectional_urg_packets',
                            'bidirectional_ack_packets', 'bidirectional_psh_packets', 'bidirectional_rst_packets' ,
                            'bidirectional_fin_packets'
                            ,
                            'src2dst_packets', 'src2dst_bytes', 'src2dst_min_ps',
                            'src2dst_mean_ps',
                            'src2dst_stddev_ps', 'src2dst_max_ps', 'src2dst_min_piat_ms',
                            'src2dst_mean_piat_ms',
                            'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms', 'src2dst_syn_packets',
                            'src2dst_cwr_packets', 'src2dst_ece_packets', 'src2dst_urg_packets',
                            'src2dst_ack_packets', 'src2dst_psh_packets', 'src2dst_rst_packets',
                            'src2dst_fin_packets'
                            ,
                            'dst2src_packets', 'dst2src_bytes', 'dst2src_min_ps',
                            'dst2src_mean_ps',
                            'dst2src_stddev_ps', 'dst2src_max_ps', 'dst2src_min_piat_ms',
                            'dst2src_mean_piat_ms',
                            'dst2src_stddev_piat_ms', 'dst2src_max_piat_ms', 'dst2src_syn_packets',
                            'dst2src_cwr_packets', 'dst2src_ece_packets', 'dst2src_urg_packets',
                            'dst2src_ack_packets', 'dst2src_psh_packets', 'dst2src_rst_packets',
                            'dst2src_fin_packets', 'label'
                            ]