#10.Sep.2023
# addr: /home/mehrdad/PycharmProjects/C2_communication/build_ids
dataset_name: 'red-team'
ids_folder: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/results/k-fold/' # put all output there
train_ds_address:
  fold0: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/train0.csv'
  fold1: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/train1.csv'
  fold2: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/train2.csv'
  fold3: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/train3.csv'
  fold4: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/train4.csv'

test_ds_address:
  fold0: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/test0.csv'
  fold1: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/test1.csv'
  fold2: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/test2.csv'
  fold3: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/test3.csv'
  fold4: '/media/sf_GAN_output/red-teaming-10-Sep-2023/4.comparison_with_CICIDSandUNSW/New DS/ds_combined/test4.csv'
whole_training: ''
deployment_test: ''
similarity_test: ''

feature_set:
  - 'bidirectional_packets'
  - 'bidirectional_bytes'
  - 'bidirectional_min_ps'
  - 'bidirectional_mean_ps'
  - 'bidirectional_stddev_ps'
  - 'bidirectional_max_ps'
  - 'bidirectional_min_piat_ms'
  - 'bidirectional_mean_piat_ms'
  - 'bidirectional_stddev_piat_ms'
  - 'bidirectional_max_piat_ms'
  - 'bidirectional_syn_packets'
  - 'bidirectional_cwr_packets'
  - 'bidirectional_ece_packets'
  - 'bidirectional_urg_packets'
  - 'bidirectional_ack_packets'
  - 'bidirectional_psh_packets'
  - 'bidirectional_rst_packets'
  - 'bidirectional_fin_packets'
  - 'src2dst_packets'
  - 'src2dst_bytes'
  - 'src2dst_min_ps'
  - 'src2dst_mean_ps'
  - 'src2dst_stddev_ps'
  - 'src2dst_max_ps'
  - 'src2dst_min_piat_ms'
  - 'src2dst_mean_piat_ms'
  - 'src2dst_stddev_piat_ms'
  - 'src2dst_max_piat_ms'
  - 'src2dst_syn_packets'
  - 'src2dst_cwr_packets'
  - 'src2dst_ece_packets'
  - 'src2dst_urg_packets'
  - 'src2dst_ack_packets'
  - 'src2dst_psh_packets'
  - 'src2dst_rst_packets'
  - 'src2dst_fin_packets'
  - 'dst2src_packets'
  - 'dst2src_bytes'
  - 'dst2src_min_ps'
  - 'dst2src_mean_ps'
  - 'dst2src_stddev_ps'
  - 'dst2src_max_ps'
  - 'dst2src_min_piat_ms'
  - 'dst2src_mean_piat_ms'
  - 'dst2src_stddev_piat_ms'
  - 'dst2src_max_piat_ms'
  - 'dst2src_syn_packets'
  - 'dst2src_cwr_packets'
  - 'dst2src_ece_packets'
  - 'dst2src_urg_packets'
  - 'dst2src_ack_packets'
  - 'dst2src_psh_packets'
  - 'dst2src_rst_packets'
  - 'dst2src_fin_packets'
  - 'label'

